### ISSUE TITLE
Your opinion and a little feedback

### ISSUE THREAD

**Issue by splitkeyseed** [capi/ssss-made-easy#1]
Hi.

It’s a nice and simple secret sharing site that you have created which makes it quite appealing to use.

I have been looking for something like this but it always bothered me a bit that I (a non-cryptographer person) don’t understand how SSSS work behind the scenes. And therefore I have been working on a similar but different solution. If you don’t mind of course I was just wondering if I could ask you your opinion on such solution.

Instead of SSSS I am using what I believe is called Substitution Cipher to create the secret shares. This has its own limitations but what I like about it is that it is somewhat easy to do recovery with pen and paper if needed. Also because of the simplicity of Substitution Cipher I believe non-cryptographers have a chance of understanding how it works, which in turn makes it easier to trust with one’s secrets. What is your opinion on such solution? I have made an app that you can try if you are interested at https://splitkeyseed.github.io/secretsharing/ to be frank I am not sure if I completely failed somewhere in my understanding or implementation of my solution, just to warn you :-)

If you are interested features that imo could make your web site more attractive to use would be an offline version (one page web site) and also a printer friendly way to print the shares as I would like to create/combine and print shares when offline for safety reasons.

Best regards

**Comment by capi** [comment]
Hi! I'm definitely going to have a look. Thank you for your feedback.
The main reason I built it on SSSS was basically Matt Parker's fun video that I also linked in the "About" section: https://www.youtube.com/watch?v=K54ildEW9-Q

I'm unfortunately not a cryptographer myself, so I don't have opinions on what's the better mathematical solution to this is. But I will have a look and try to educate myself.
